/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ChatflowRouteRouteImport } from './routes/chatflow/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as ChatRoomsIndexRouteImport } from './routes/chatRooms/index'
import { Route as ChatflowNodeIdRouteImport } from './routes/chatflow/$nodeId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatflowRouteRoute = ChatflowRouteRouteImport.update({
  id: '/chatflow',
  path: '/chatflow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomsIndexRoute = ChatRoomsIndexRouteImport.update({
  id: '/chatRooms/',
  path: '/chatRooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatflowNodeIdRoute = ChatflowNodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => ChatflowRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatflow': typeof ChatflowRouteRouteWithChildren
  '/test': typeof TestRoute
  '/chatflow/$nodeId': typeof ChatflowNodeIdRoute
  '/chatRooms': typeof ChatRoomsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/login': typeof LoginIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatflow': typeof ChatflowRouteRouteWithChildren
  '/test': typeof TestRoute
  '/chatflow/$nodeId': typeof ChatflowNodeIdRoute
  '/chatRooms': typeof ChatRoomsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/login': typeof LoginIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatflow': typeof ChatflowRouteRouteWithChildren
  '/test': typeof TestRoute
  '/chatflow/$nodeId': typeof ChatflowNodeIdRoute
  '/chatRooms/': typeof ChatRoomsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatflow'
    | '/test'
    | '/chatflow/$nodeId'
    | '/chatRooms'
    | '/groups'
    | '/login'
    | '/settings'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatflow'
    | '/test'
    | '/chatflow/$nodeId'
    | '/chatRooms'
    | '/groups'
    | '/login'
    | '/settings'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/chatflow'
    | '/test'
    | '/chatflow/$nodeId'
    | '/chatRooms/'
    | '/groups/'
    | '/login/'
    | '/settings/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatflowRouteRoute: typeof ChatflowRouteRouteWithChildren
  TestRoute: typeof TestRoute
  ChatRoomsIndexRoute: typeof ChatRoomsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatflow': {
      id: '/chatflow'
      path: '/chatflow'
      fullPath: '/chatflow'
      preLoaderRoute: typeof ChatflowRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatRooms/': {
      id: '/chatRooms/'
      path: '/chatRooms'
      fullPath: '/chatRooms'
      preLoaderRoute: typeof ChatRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatflow/$nodeId': {
      id: '/chatflow/$nodeId'
      path: '/$nodeId'
      fullPath: '/chatflow/$nodeId'
      preLoaderRoute: typeof ChatflowNodeIdRouteImport
      parentRoute: typeof ChatflowRouteRoute
    }
  }
}

interface ChatflowRouteRouteChildren {
  ChatflowNodeIdRoute: typeof ChatflowNodeIdRoute
}

const ChatflowRouteRouteChildren: ChatflowRouteRouteChildren = {
  ChatflowNodeIdRoute: ChatflowNodeIdRoute,
}

const ChatflowRouteRouteWithChildren = ChatflowRouteRoute._addFileChildren(
  ChatflowRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatflowRouteRoute: ChatflowRouteRouteWithChildren,
  TestRoute: TestRoute,
  ChatRoomsIndexRoute: ChatRoomsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
